name: mercuryeditions
favicon: null
layout_spectrum: 0.8003988426644355
typography_spectrum: 0.021877826657146215
title: Mercury Editions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfef9'
    - '#010100'
    - '#c4c5bd'
    - '#585951'
    - '#bf1c00'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
